### ISSUE TITLE
hacking_files/vmlinux out of date?

### ISSUE THREAD

**Issue by manuelafm** [ucb-bar/riscv-qemu#2]
Hi,

I believe that the content of hacking_files/vmlinux is now out of date.

I tried to compile my binaries and run them under qemu (qemu updated and recompiled yesterday, and binaries also recompiled with the new ABI unless I made some mistake); but the binaries won't run when I use the kernels in hacking_files/vmlinux to run inside qemu (I can paste the error when starting the binaries, if it's of any use).

I tried to compile a kernel myself, but qemu or the kernel segfault before printing anything useful, I don't know exactly what's wrong either.

So it would be great if these kernels could be updated to run the latest binaries, so I least people can see if their programs and compiled binaries are working fine.

Cheers and thanks.

**Comment by sagark** [comment]
I've updated the README to point to the latest images from the RISC-V Getting Started guide. These are ABI-compatible with the latest toolchain.

You can also find instructions for building your own qemu-compatible version of riscv-linux here: http://riscv.org/workshop-jan2015/RISCV_Soft_Stack_Bootcamp.pdf

**Comment by manuelafm** [comment]
Worked fine, thank you!
